# Site wide configuration

title:            stefan's techblog
locale:           en_US
url:              https://techblog.lankes.org


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
permalink: pretty
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

scholar:
  style: assets/bibliography/ieee-with-url.csl
  locale: en
 
  sort_by: year,month
  order: descending
  bibliography_list_tag: ul
 
  source: _bibliography
  repository: pdf
  bibliography: references
  bibliography_template: bibliography
 
  replace_strings: true
 
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
 
  query: "@*"

# Site owner
owner:
  name: Stefan Lankes
  avatar: bio-photo.jpg
  bio: #"Describe your self."
  email: stefan@lankes.org
  disqus-shortname: stefanstechblog 
  twitter: stlankes
  facebook: #username
  google:
    plus: StefanLankes
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: stlankes
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: stlankes
  xing: Stefan_Lankes
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["helpers", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
